
title: 晴読雨読
description: >
  My Description. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
baseurl: "/dokusyo-kansobun-jekyll-theme"
url: "https://6uclz1.github.io"

author:
  name: 6uclz1
  email: mail@example.com

paginate: 3
paginate_path: page:num

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed
